pub const ASCII: &[(u8, &str, &str, &str)] = &[
    (0x00, "NUL", "Null char", "空字符"),
    (0x01, "SOH", "Start of Heading", "标题开始"),
    (0x02, "STX", "Start of Text", "正文开始"),
    (0x03, "ETX", "End of Text", "正文结束"),
    (0x04, "EOT", "End of Transmission", "传输结束"),
    (0x05, "ENQ", "Enquiry", "查询"),
    (0x06, "ACK", "Acknowledgment", "确认"),
    (0x07, "BEL", "Bell", "振铃"),
    (0x08, "BS", "Back Space", "退格"),
    (0x09, "HT", "Horizontal Tab", "水平制表符"),
    (0x0A, "LF", "Line Feed", "换行键"),
    (0x0B, "VT", "Vertical Tab", "垂直制表符"),
    (0x0C, "FF", "Form Feed", "换页键"),
    (0x0D, "CR", "Carriage Return", "回车键"),
    (0x0E, "SO", "Shift Out / X-On", "移出"),
    (0x0F, "SI", "Shift In / X-Off", "移入"),
    (0x10, "DLE", "Data Line Escape", "数据链路转义"),
    (0x11, "DC1", "Device Control 1", "设备控制 1"),
    (0x12, "DC2", "Device Control 2", "设备控制 2"),
    (0x13, "DC3", "Device Control 3", "设备控制 3"),
    (0x14, "DC4", "Device Control 4", "设备控制 4"),
    (0x15, "NAK", "Negative Acknowledgement", "反确认"),
    (0x16, "SYN", "Synchronous Idle", "同步空闲"),
    (0x17, "ETB", "End of Transmit Block", "传输块结束"),
    (0x18, "CAN", "Cancel", "取消"),
    (0x19, "EM", "End of Medium", "介质中断"),
    (0x1A, "SUB", "Substitute", "替换"),
    (0x1B, "ESC", "Escape", "转义"),
    (0x1C, "FS", "File Separator", "文件分隔符"),
    (0x1D, "GS", "Group Separator", "组分隔符"),
    (0x1E, "RS", "Record Separator", "记录分离符"),
    (0x1F, "US", "Unit Separator", "单元分隔符"),
];

